src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BookRepository::class)
 */
class Book
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="date")
     */
    private $release_date;

    /**
     * @ORM\Column(type="integer")
     */
    private $length;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $genres;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $user_readable;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $admin_readable;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getReleaseDate(): ?\DateTimeInterface
    {
        return $this->release_date;
    }

    public function setReleaseDate(\DateTimeInterface $release_date): self
    {
        $this->release_date = $release_date;

        return $this;
    }

    public function getLength(): ?int
    {
        return $this->length;
    }

    public function setLength(int $length): self
    {
        $this->length = $length;

        return $this;
    }

    public function getGenres(): ?string
    {
        return $this->genres;
    }

    public function setGenres(string $genres): self
    {
        $this->genres = $genres;

        return $this;
    }

    public function getUserReadable(): ?string
    {
        return $this->user_readable;
    }

    public function setUserReadable(string $user_readable): self
    {
        $this->user_readable = $user_readable;

        return $this;
    }

    public function getAdminReadable(): ?string
    {
        return $this->admin_readable;
    }

    public function setAdminReadable(string $admin_readable): self
    {
        $this->admin_readable = $admin_readable;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="fos_user")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    public function __construct()
    {
        parent::__construct();
        // your own logic
    }
}

src/Controller/BookController.php
<?php


namespace App\Controller;

use App\Repository\BookRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;

class BookController extends AbstractController
{
    /**
     * @param BookRepository $repository
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function index(BookRepository $repository)
    {
        if (!$this->getUser()) {
            return $this->redirect('/login');
        }

        $books = $repository->findAllBooks();

        if ($this->getUser()->getUsername() === 'admin') {
            $books = $books->where('book.admin_readable = :temp')->setParameter('temp', 'Yes');
        } else {
            $books = $books->where('book.user_readable = :temp')->setParameter('temp', 'Yes');
        }

        if (!$books) {
            throw $this->createNotFoundException(
                'No books found'
            );
        }

        return $this->render('book/index.html.twig',[
            'books' => $books->getQuery()->getResult()
        ]);
    }

    /**
     * @param BookRepository $repository
     * @param Request $request
     * @return JsonResponse
     */
    public function loadMore(BookRepository $repository, Request $request)
    {
        $lastId = $request->request->get('lastId');
        return new JsonResponse($repository->findMoreBooks($lastId));
    }

    /**
     * @param BookRepository $repository
     * @param $id
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function showBookDetails(BookRepository $repository,$id)
    {
        return $this->render('book/show_details.html.twig',[
            'books' => $repository->find($id)
        ]);
    }

    /**
     * @param BookRepository $repository
     * @param $genre
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function showBooksInGenre(BookRepository $repository, $genre)
    {
        return $this->render('book/show_genres.html.twig',[
            'books' => $repository->findBooksInSameGenre($genre)
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    <body>
        {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
            {{ 'layout.logged_in_as'|trans({'%username%': app.user.username}, 'FOSUserBundle') }} |
            <a href="{{ path('fos_user_security_logout') }}">
                {{ 'layout.logout'|trans({}, 'FOSUserBundle') }}
            </a>
        {% else %}
            <a href="{{ path('fos_user_security_login') }}">{{ 'layout.login'|trans({}, 'FOSUserBundle') }}</a>
        {% endif %}
        {% block body %}{% endblock %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/book/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Home Page {% endblock %}

{% block body %}
<div class="container">
    <h2 class="p-4">List of Books</h2>
    {% include('./book/table.html.twig') %}
    <button class="button btn btn-info">Load More</button>
</div>
{% endblock %}
{% block javascripts %}
<script>
    $(document).ready(function() {
        $('.button').click(function () {
            var lastId = 0;
            $('.id').each(function()
            {
                $this = parseInt( $(this).text() );
                if ($this > lastId) lastId = $this;
            });

            $.ajax({
                type: 'POST',
                url: '/load',
                data: {lastId: lastId},
                dataType: 'json',
                success: function (data) {
                    for(i = 0; i < data.length; i++) {
                       let book  = data[i];
                       let genres = book['genres'].split(',');

                        $('#books tr:last').after('<tr>' +
                            '<td><a href="/book/'+ book['id']+'">'+ book['name'] +'</a></td>' +
                            '<td>'+ book['release_date'] +'</td>' +
                            '<td>'+ book['length'] +'</td>' +
                            '<td><ul id='+ i + '></ul></td>'+
                            '<td>'+ book['user_readable'] +'</td>' +
                            '<td>'+ book['admin_readable'] +'</td>' +
                            '<td class="id" style="display: none">'+ book['id'] +'</td>' +
                            '</tr>');

                        $.each(genres, function(index, value) {
                            $('#'+i).append('<li><a href="/genre/'+ value+'">'+value+'</a></li>')
                        })
                    }
                },
                error: function (xhr, textStatus, errorThrown) {
                    $('.button'). attr('disabled', true)
                   alert('There is no more data')
                }
            });
        });
    });
</script>
{% endblock %}

templates/book/show_details.html.twig
{% extends 'base.html.twig' %}

{% block title %} Book Details {% endblock %}

{% block body %}
<div class="container">
    <h2 class="p-4">Book Details</h2>
    <div class="pb-3">
        <a class="btn btn-primary" href="{{ path('index') }}">Back to Homepage</a>
    </div>
    {% include('./book/table.html.twig') %}
</div>
{% endblock %}

templates/book/show_genres.html.twig
{% extends 'base.html.twig' %}

{% block title %} Display all Books in this Genre {% endblock %}

{% block body %}
<div class="container">
    <h2 class="p-4">All Books in this Genre</h2>
    <div class="pb-3">
        <a class="btn btn-primary" href="{{ path('index') }}">Back to Homepage</a>
    </div>
    {% include('./book/table.html.twig') %}
</div>
{% endblock %}

templates/book/table.html.twig
<table class="table table-striped" id="books">
    <thead>
        <tr>
            <td>Name</td>
            <td>Release Date</td>
            <td>Length</td>
            <td class="pl-5">Genres</td>
            <td>User Readable</td>
            <td>Admin Readable</td>
        </tr>
    </thead>

    {% if books is iterable %}
        {% for book in books %}
            <tr>
            <td><a href="{{ path('book',{'id' : book.id}) }}">{{ book.name }}</a></td>
            <td>{{ book.releaseDate|date('d-m-Y') }}</td>
            <td>{{ book.length }}</td>
            <td>
                {% set genres = book.genres|split(',') %}
                <ul>
                    {% for genre in genres %}
                        <li>
                            <a href="{{ path('genre',{'genre' : genre}) }}">{{ genre }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </td>
            <td>{{ book.userReadable }}</td>
            <td>{{ book.adminReadable }}</td>
            <td class="id" style="display: none">{{ book.id }}</td>
        </tr>
        {% endfor %}
    {% else %}
        <tr>
            <td><a href="{{ path('book',{'id' : books.id}) }}">{{ books.name }}</a></td>
            <td>{{ books.releaseDate|date('d-m-Y') }}</td>
            <td>{{ books.length }}</td>
            <td>
                {% set genres = books.genres|split(',') %}
                <ul>
                    {% for genre in genres %}
                        <li>
                            <a href="{{ path('genre',{'genre' : genre}) }}">{{ genre }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </td>
            <td>{{ books.userReadable }}</td>
            <td>{{ books.adminReadable }}</td>
        </tr>
    {% endif %}
</table>